exclude: "src/gjk/sema/"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        stages: [pre-commit, pre-push, manual]
        exclude: "CodeGenerationTools/.*"
      - id: trailing-whitespace
        stages: [pre-commit, pre-push, manual]
        exclude: "CodeGenerationTools/.*"

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: [--py312-plus]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: ["--select", "I"]
      - id: ruff-format
