"""Tests layout.event type, version 000"""

from gjk.named_types import LayoutEvent


def test_layout_event_generated() -> None:
    d = {
        "MessageId": "1302c0f8-1983-43b2-90d2-61678d731db3",
        "TimeCreatedMs": 1728651445746,
        "Src": "hw1.isone.me.versant.keene.beech.scada",
        "Layout": {
            "FromGNodeAlias": "hw1.isone.me.versant.keene.beech.scada",
            "FromGNodeInstanceId": "98542a17-3180-4f2a-a929-6023f0e7a106",
            "MessageCreatedMs": 1728651445746,
            "MessageId": "1302c0f8-1983-43b2-90d2-61678d731db3",
            "ZoneList": ["Down", "Up"],
            "DataChannels": [
                {
                    "Name": "hp-idu-pwr",
                    "DisplayName": "Hp IDU",
                    "AboutNodeName": "hp-idu-pwr",
                    "CapturedByNodeName": "power-meter",
                    "TelemetryName": "PowerW",
                    "TerminalAssetAlias": "hw1.isone.me.versant.keene.beech.ta",
                    "InPowerMetering": True,
                    "StartS": 1721405699,
                    "Id": "50cf426b-ff3f-4a30-8415-8d3fba5e0ab7",
                    "TypeName": "data.channel.gt",
                    "Version": "001",
                }
            ],
            "TankModuleComponents": [
                {
                    "ComponentAttributeClassId": "f88fbf89-5b74-46d6-84a3-8e7494d08435",
                    "ComponentId": "8aef0b11-5a1c-415e-b40e-d277e0ff4403",
                    "ConfigList": [
                        {
                            "AsyncCapture": True,
                            "CapturePeriodS": 60,
                            "ChannelName": "buffer-depth1",
                            "Exponent": 3,
                            "TypeName": "channel.config",
                            "Unit": "Celcius",
                            "Version": "000",
                        },
                        {
                            "AsyncCapture": True,
                            "CapturePeriodS": 60,
                            "ChannelName": "buffer-depth2",
                            "Exponent": 3,
                            "TypeName": "channel.config",
                            "Unit": "Celcius",
                            "Version": "000",
                        },
                        {
                            "AsyncCapture": True,
                            "CapturePeriodS": 60,
                            "ChannelName": "buffer-depth3",
                            "Exponent": 3,
                            "TypeName": "channel.config",
                            "Unit": "Celcius",
                            "Version": "000",
                        },
                        {
                            "AsyncCapture": True,
                            "CapturePeriodS": 60,
                            "ChannelName": "buffer-depth4",
                            "Exponent": 3,
                            "TypeName": "channel.config",
                            "Unit": "Celcius",
                            "Version": "000",
                        },
                        {
                            "AsyncCapture": True,
                            "AsyncCaptureDelta": 2000,
                            "CapturePeriodS": 60,
                            "ChannelName": "buffer-depth1-micro-v",
                            "Exponent": 6,
                            "TypeName": "channel.config",
                            "Unit": "VoltsRms",
                            "Version": "000",
                        },
                        {
                            "AsyncCapture": True,
                            "AsyncCaptureDelta": 2000,
                            "CapturePeriodS": 60,
                            "ChannelName": "buffer-depth2-micro-v",
                            "Exponent": 6,
                            "TypeName": "channel.config",
                            "Unit": "VoltsRms",
                            "Version": "000",
                        },
                        {
                            "AsyncCapture": True,
                            "AsyncCaptureDelta": 2000,
                            "CapturePeriodS": 60,
                            "ChannelName": "buffer-depth3-micro-v",
                            "Exponent": 6,
                            "TypeName": "channel.config",
                            "Unit": "VoltsRms",
                            "Version": "000",
                        },
                        {
                            "AsyncCapture": True,
                            "AsyncCaptureDelta": 2000,
                            "CapturePeriodS": 60,
                            "ChannelName": "buffer-depth4-micro-v",
                            "Exponent": 6,
                            "TypeName": "channel.config",
                            "Unit": "VoltsRms",
                            "Version": "000",
                        },
                    ],
                    "DisplayName": "buffer PicoTankModule",
                    "Enabled": True,
                    "SerialNumber": "1030",
                    "NumSampleAverages": 10,
                    "PicoAHwUid": "pico_4c1a21",
                    "PicoBHwUid": "pico_487a22",
                    "PicoKOhms": 30,
                    "Samples": 1000,
                    "SendMicroVolts": True,
                    "TempCalcMethod": "SimpleBetaForPico",
                    "ThermistorBeta": 3977,
                    "TypeName": "pico.tank.module.component.gt",
                    "Version": "000",
                }
            ],
            "FlowModuleComponents": [
                {
                    "AsyncCaptureThresholdGpmTimes100": 5,
                    "ComponentAttributeClassId": "aa4ad342-883a-4f89-bf86-9eb430aeb308",
                    "ComponentId": "b505a781-1671-467f-af8f-6d0ad7aca172",
                    "ConfigList": [
                        {
                            "AsyncCapture": True,
                            "CapturePeriodS": 10,
                            "ChannelName": "primary-flow",
                            "Exponent": 2,
                            "TypeName": "channel.config",
                            "Unit": "Gpm",
                            "Version": "000",
                        },
                        {
                            "AsyncCapture": True,
                            "CapturePeriodS": 10,
                            "ChannelName": "primary-flow-hz",
                            "Exponent": 6,
                            "TypeName": "channel.config",
                            "Unit": "VoltsRms",
                            "Version": "000",
                        },
                    ],
                    "ConstantGallonsPerTick": 0.0748,
                    "CutoffFrequency": 1.25,
                    "DisplayName": "Primary Flow ReedFlowModule",
                    "Enabled": True,
                    "FlowMeterType": "EKM__HOTSPWM075HD",
                    "FlowNodeName": "primary-flow",
                    "GpmFromHzMethod": "Constant",
                    "HwUid": "pico_1b5636",
                    "HzCalcMethod": "BasicExpWeightedAvg",
                    "NoFlowMs": 5000,
                    "PublishAnyTicklistAfterS": 10,
                    "PublishTicklistLength": 10,
                    "SendGallons": False,
                    "SendHz": True,
                    "SendTickLists": False,
                    "SerialNumber": "NA",
                    "TypeName": "pico.flow.module.component.gt",
                    "Version": "000",
                }
            ],
            "TypeName": "layout.lite",
            "Version": "000",
        },
        "TypeName": "layout.event",
        "Version": "000",
    }

    assert LayoutEvent.from_dict(d).to_dict() == d
