"""create message and scada table

Revision ID: 08bb9e1becc1
Revises: 
Create Date: 2024-07-14 13:15:58.792649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08bb9e1becc1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('from_alias', sa.String(), nullable=False),
    sa.Column('type_name', sa.String(), nullable=False),
    sa.Column('message_persisted_ms', sa.BigInteger(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('message_created_ms', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('scada',
    sa.Column('g_node_id', sa.String(), nullable=False),
    sa.Column('g_node_alias', sa.String(), nullable=False),
    sa.Column('short_alias', sa.String(), nullable=False),
    sa.Column('scada_installed_s', sa.Integer(), nullable=True),
    sa.Column('ta_fully_installed_s', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('g_node_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scada')
    op.drop_table('messages')
    # ### end Alembic commands ###
