"""add start_s to data_channel

Revision ID: 2bfd96639dd9
Revises: 37ce3bbd137e
Create Date: 2024-07-19 13:18:55.378714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bfd96639dd9'
down_revision: Union[str, None] = '37ce3bbd137e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_channel', sa.Column('start_s', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_channel', 'start_s')
    # ### end Alembic commands ###
