"""create data_channel table

Revision ID: 37ce3bbd137e
Revises: 08bb9e1becc1
Create Date: 2024-07-16 17:43:49.210132

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "37ce3bbd137e"
down_revision: Union[str, None] = "08bb9e1becc1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_channel",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("about_node_name", sa.String(), nullable=False),
        sa.Column("captured_by_node_name", sa.String(), nullable=False),
        sa.Column("telemetry_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data_channel")
    # ### end Alembic commands ###
