"""Nodal Hourly Energy

Revision ID: 391fc0462f5a
Revises: 8307576a573f
Create Date: 2024-08-09 07:27:22.600755

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "391fc0462f5a"
down_revision: Union[str, None] = "8307576a573f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nodal_hourly_energy",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("hour_start_s", sa.BigInteger(), nullable=True),
        sa.Column("power_channel_id", sa.String(), nullable=False),
        sa.Column("watt_hours", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["power_channel_id"],
            ["data_channels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "hour_start_s", "power_channel_id", name="unique_time_channel"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nodal_hourly_energy")
    # ### end Alembic commands ###
