"""drop_readings

Revision ID: b371e63f0b02
Revises: 2d8b1ad23a72
Create Date: 2025-12-15 15:00:18.255630

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b371e63f0b02'
down_revision: Union[str, None] = '2d8b1ad23a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_data_channel_time', table_name='readings')
    op.drop_index('ix_message_id', table_name='readings')
    op.drop_table('readings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    raise RuntimeError(
        "readings table is derived data and intentionally not restored on downgrade"
    )