"""add uniqueness constraint to messages

Revision ID: ed9df502fb56
Revises: b829ccf129c3
Create Date: 2024-07-31 13:39:18.902851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed9df502fb56'
down_revision: Union[str, None] = 'b829ccf129c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_from_type_message', 'messages', ['from_alias', 'type_name', 'message_persisted_ms'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_from_type_message', 'messages', type_='unique')
    # ### end Alembic commands ###
